import { mockGrievances } from '@/lib/data';
import { summarizeGrievance } from '@/ai/flows/summarize-grievance';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Bot } from 'lucide-react';

type GrievanceWithSummary = (typeof mockGrievances)[0] & { summary?: string; };

export default async function AdminGrievancesPage() {

  const grievancesWithSummaries: GrievanceWithSummary[] = await Promise.all(
    mockGrievances.map(async (grievance) => {
      try {
        const result = await summarizeGrievance({ grievanceText: grievance.description || 'No description provided.' });
        return { ...grievance, summary: result.summary };
      } catch (e) {
        console.error(`Failed to summarize grievance ${grievance.id}:`, e);
        return { ...grievance, summary: "AI summary unavailable." };
      }
    })
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-headline text-3xl font-bold tracking-tight">
          Grievance Inbox
        </h1>
        <p className="text-muted-foreground">
          Review and manage all submitted grievances.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>All Grievances</CardTitle>
          <CardDescription>Summaries are generated by AI to help you quickly assess each issue.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>ID</TableHead>
                <TableHead>Related Case</TableHead>
                <TableHead>Subject</TableHead>
                <TableHead className="flex items-center gap-2"><Bot className="h-4 w-4" /> AI Summary</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {grievancesWithSummaries.map((g) => (
                <TableRow key={g.id}>
                  <TableCell className="font-mono text-xs">{g.id}</TableCell>
                  <TableCell className="font-mono text-xs">{g.caseId}</TableCell>
                  <TableCell className="font-medium">{g.subject}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">{g.summary}</TableCell>
                  <TableCell>
                    <Badge variant={g.status === 'Resolved' ? 'default' : g.status === 'In Progress' ? 'secondary' : 'outline'}>
                      {g.status}
                    </Badge>
                  </TableCell>
                  <TableCell>{g.date}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
